stages:
  - build
  - test
  - deploy

services:
  - name: docker:dind
    command: ["--experimental"]

before_script:
  - apk --no-cache add git just

image: docker:git

.matrix:
  parallel:
    matrix:
      - PLATFORM:
          - "linux/amd64"
        VERSION:
          - "3.14"
          - "3.15"
          - "3.16"
          - "3.17"
          - "latest"

build:
  artifacts:
    paths:
      - .cache
    expire_in: 1 hour
  extends:
    - .matrix
  stage: build
  script:
    - just build "${VERSION}" "${PLATFORM}"
    - just run
    - docker stop alpine-ansible
    # Upload internally for testing
    - >
      just
      USER="${CI_REGISTRY_USER}"
      PASSWORD="${CI_REGISTRY_PASSWORD}"
      REGISTRY="${CI_REGISTRY}"
      REPOSITORY="${CI_REGISTRY_IMAGE}"
      upload "${VERSION}" "${PLATFORM}"

scan:
  dependencies: []
  image:
    name: aquasec/trivy
    entrypoint: [""]
  stage: test
  script:
    - just scan "${CI_REGISTRY_IMAGE}"

deploy:
  extends:
    - .matrix
  only:
    - master
  retry: 1
  stage: deploy
  script:
    - just upload "${VERSION}" "${PLATFORM}"
